apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
    ### Create a name for your PVC ###
    name: vectorsink-esa-pvc
    ### Use a namespace that matched your intended consuming pod, or "default" ###
    namespace: azure-iot-operations
spec: 
    accessModes: 
        - ReadWriteMany 
    resources: 
        requests: 
            storage: 5Gi 
    storageClassName: esa
    volumeMode: Filesystem
    ### This name references your PV name in your PV config ###
    volumeName: vectorsink-esa-pv
status: 
    accessModes: 
        - ReadWriteMany 
    capacity: 
        storage: 5Gi
