---
apiVersion: apps/v1
#apiVersion: v1
kind: Deployment
metadata:
  name: multi-agent-agents-workload
  namespace: azure-iot-operations
  labels:
    app: multi-agent-agents-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-agent-agents-workload
  template:
    metadata:
      labels:
        app: multi-agent-agents-workload

    spec:
      imagePullSecrets:
         - name: cctestotdata

      containers:
        - name: multi-agent-agents
          image: ccselftestacr.azurecr.io/multi-agent-agents:v35
          imagePullPolicy: Always
          # ports:  
          # - containerPort: 5002
          
       

---
kind: Service
apiVersion: v1
metadata:
  name: multi-agent-agents-service
  namespace: azure-iot-operations
  labels:
    app: multi-agent-agents-workload
spec:
  selector:
    app: multi-agent-agents-workload
  ports:
    - protocol: TCP
      port: 8801
      targetPort: 8801
  type: LoadBalancer
